<a href="https://colab.research.google.com/github/Qophy/PBML/blob/DataSet/data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import sys
#import tensorflow as tf
import pandas as pd
import numpy as np
#import numpy as np
#import matplotlib.pyplot as plt
#import seaborn as sns

In [ ]:
os.listdir('/content/drive/My Drive/code')

['INWSStaticDataGroupedByTimestamp1.xlsx',
 'pinns_tf2-main',
 'PINN-PDE(utube)',
 'PINNs-master(I)']

In [ ]:
# Define the path to your modules directory on Google Drive
# Adjust 'My Drive/your_project_folder' if your modules are in a different location
data_path = '/content/drive/My Drive/code/'

# Add the modules_path to sys.path if it's not already there
if data_path not in sys.path:
    sys.path.append(data_path)

In [ ]:
os.listdir(data_path)

['INWSStaticDataGroupedByTimestamp1.xlsx',
 'pinns_tf2-main',
 'PINN-PDE(utube)',
 'PINNs-master(I)']

In [ ]:
dataset = pd.read_excel(data_path + 'INWSStaticDataGroupedByTimestamp1.xlsx')

In [ ]:
dataset.shape

(29842, 8)

In [ ]:
data_node1 = dataset[dataset["Node Id"] == 1].copy()
data_node2 = dataset[dataset["Node Id"] == 2].copy()

In [ ]:
dataset.sample(10)

,Id,Node Id,Timestamp,Timestamp as DateTime,Temperature,Conductivity,pH,DissolvedOxygen
20617,20618,1,201512252133560992,2015-12-25 21:33:56,NaN,NaN,NaN,8.1
24500,24501,2,201506072052569984,2015/06/07 20:52:57 0000,19.07,355.5,6.06,32.0
2483,2484,1,201507021018190016,2015/07/02 10:18:19 0000,15.89,392.2,7.18,40.4
10764,10765,1,201509212311310016,2015/09/21 23:11:31 0000,14.12,356.2,6.28,14.4
3518,3519,1,201507110012470016,2015/07/11 00:12:47 0000,20.11,499.8,7.66,4.5
20805,20806,1,201512260551519008,2015-12-26 05:51:51,NaN,NaN,NaN,6.0
25718,25719,2,201506161158300000,2015/06/16 11:58:30 0000,19.13,357.7,6.78,40.2
20337,20338,1,201512250525260992,2015-12-25 05:25:26,NaN,NaN,NaN,8.1
13620,13621,1,201510240528070016,2015/10/24 05:28:07 0000,9.66,265.4,4.80,29.9
14322,14323,1,201511021035160000,2015/11/02 10:35:16 0000,8.22,255.4,6.07,36.6

## Find and Drop NaNs in the DATASET.

In [ ]:
def print_rows_with_nans(df):
    nan_rows = df[df.isna().any(axis=1)]
    if nan_rows.empty:
        print(f"\n✅ No NaN values found in the dataset.")
    else:
        print(f"\n⚠️ Found {len(nan_rows)} rows with NaN values.")
        # print((nan_rows))

    return nan_rows

In [ ]:
print_rows_with_nans(dataset)

⚠️ Found 4642 rows with NaN values.

,Id,Node Id,Timestamp,Timestamp as DateTime,Temperature,Conductivity,pH,DissolvedOxygen
0,1,1,201505011710380000,2015/05/01 17:10:38 0000,15.12,345.3,NaN,NaN
220,221,1,201505161519360000,2015/05/16 15:19:36 0000,16.06,370.1,NaN,69.5
376,377,1,201505291858129984,2015/05/29 18:58:13 0000,NaN,324.9,7.76,6.2
377,378,1,201505291902060000,2015/05/29 19:02:06 0000,14.74,325.0,NaN,5.7
3752,3753,1,201507140738500000,2015/07/14 07:38:50 0000,20.97,562.8,NaN,5.6
...,...,...,...,...,...,...,...,...
23069,23070,1,201601052108076992,2016-01-05 21:08:07,NaN,NaN,6.26,NaN
23070,23071,1,201601052108100000,2016/01/05 21:08:10 0000,NaN,NaN,NaN,9.4
23071,23072,1,201601052108100992,2016-01-05 21:08:10,NaN,257.2,NaN,NaN
23072,23073,1,201601052108124000,2016-01-05 21:08:12,2.59,NaN,NaN,NaN
23299,23300,2,201505120911200000,2015/05/12 09:11:20 0000,13.14,284.0,NaN,57.8

In [ ]:
nan_row_indices = print_rows_with_nans(dataset).index.tolist()

⚠️ Found 4642 rows with NaN values.

In [ ]:
def drop_nan_rows(list_indices):
  dataset_shape = dataset.shape
  dataset_cleaned = dataset.drop(nan_row_indices)
  dataset_cleaned_shape = dataset_cleaned.shape

  return [dataset_cleaned, dataset_cleaned_shape, dataset_shape]

In [ ]:
#wq_data = drop_nan_rows(nan_row_indices)[0].drop(columns=["DissolvedOxygen", "Timestamp"])
wq_data = drop_nan_rows(nan_row_indices)[0].drop(columns=["Timestamp"])
print(wq_data.sample(5))

          Id  Node Id     Timestamp as DateTime  Temperature  Conductivity  \
28178  28179        2  2015/07/18 07:40:31 0000        19.95         385.9
14399  14400        1  2015/11/02 23:39:01 0000         8.00         245.9
11364  11365        1  2015/09/26 20:39:39 0000        14.83         312.6
1565    1566        1  2015/06/09 13:22:54 0000        26.58         386.8
15157  15158        1  2015/11/08 16:04:53 0000         7.87         232.6

         pH  DissolvedOxygen
28178  7.76            148.2
14399  6.31             57.5
11364  6.06             17.1
1565   8.06             91.0
15157  6.27             60.8

In [ ]:
def print_negative_rows(df, columns=None, verbose=None):
    """
    Prints rows that contain negative values.

    Parameters:
        df (pd.DataFrame): Input dataset
        columns (list): Columns to check (default: all numeric columns)
    """
    if columns is None:
        columns = df.select_dtypes(include=['number']).columns

    negative_mask = (df[columns] < 0).any(axis=1)
    negative_rows = df[negative_mask]
    if verbose:
      print("Rows containing negative values:")
      print(negative_rows)

    return negative_rows

In [ ]:
columns = ["Temperature",	"Conductivity",	"pH",	"DissolvedOxygen"]
print_negative_rows(wq_data, columns=columns, verbose=0)
negative_row_indices = print_negative_rows(wq_data, columns=columns).index.tolist()

In [ ]:
wq_data = wq_data.drop(negative_row_indices)

In [ ]:
wq_data.shape

(23629, 7)

## Cascading wq_data into two different measuring points

In [ ]:
wq_data_node1 = wq_data[wq_data["Node Id"] == 1].copy()
wq_data_node2 = wq_data[wq_data["Node Id"] == 2].copy()

In [ ]:
wq_data_node1.sample(5)

,Id,Node Id,Timestamp as DateTime,Temperature,Conductivity,pH,DissolvedOxygen
9546,9547,1,2015/09/12 14:29:28 0000,15.66,359.7,1.72,17.5
6942,6943,1,2015/08/20 00:29:24 0000,18.42,337.3,4.24,9.4
5621,5622,1,2015/08/10 00:56:09 0000,19.98,326.4,4.35,7.7
6770,6771,1,2015/08/18 19:08:23 0000,17.81,322.2,4.80,7.8
11846,11847,1,2015/09/30 23:57:46 0000,12.06,290.1,6.44,24.0

In [ ]:
wq_data_node2.sample(5)

,Id,Node Id,Timestamp as DateTime,Temperature,Conductivity,pH,DissolvedOxygen
26506,26507,2,2015/06/22 02:37:52 0000,51.75,5314.6,92.61,74.9
27717,27718,2,2015/07/05 12:35:28 0000,19.36,388.7,7.75,19.3
24231,24232,2,2015/06/05 23:14:54 0000,19.10,355.2,6.40,19.4
23683,23684,2,2015/06/02 02:19:09 0000,16.99,315.0,7.62,12.6
26629,26630,2,2015/06/22 23:29:49 0000,13.35,338.9,6.76,11.0

In [ ]:
wq_data_node1.shape

(18378, 7)

# Create a FOLDER and name it PINN_WQS_dataset

In [ ]:
#os.makedirs('/content/drive/My Drive/PINN_WQS_dataset', exist_ok=True)

In [ ]:
#os.listdir('/content/drive/My Drive/PINN_WQS_dataset')

[]

# Save files to PINN_WQS_dataset directory

In [ ]:
#wq_data_node1.to_csv('/content/drive/My Drive/PINN_WQS_dataset/wq_dataset_node_1.csv', index=False)

In [ ]:
#wq_data_node2.to_csv('/content/drive/My Drive/PINN_WQS_dataset/wq_dataset_node_2.csv', index=False)

# Convert the TimeStamp feature into Cyclic features

In [ ]:
wq_data_node1["Time"] = pd.to_datetime(wq_data_node1["Timestamp as DateTime"].str[:-5], format='%Y/%m/%d %H:%M:%S')
wq_data_node2["Time"] = pd.to_datetime(wq_data_node2["Timestamp as DateTime"].str[:-5], format='%Y/%m/%d %H:%M:%S')

In [ ]:
wq_data_node1.tail()

,Id,Node Id,Timestamp as DateTime,Temperature,Conductivity,pH,DissolvedOxygen,Time
22028,22029,1,2016/01/01 16:06:56 0000,2.60,244.2,6.27,7.2,2016-01-01 16:06:56
22029,22030,1,2016/01/01 16:17:06 0000,2.62,244.3,6.26,7.3,2016-01-01 16:17:06
22030,22031,1,2016/01/01 16:27:17 0000,2.57,244.0,6.25,8.3,2016-01-01 16:27:17
22031,22032,1,2016/01/01 16:37:28 0000,2.51,243.3,6.26,6.9,2016-01-01 16:37:28
22032,22033,1,2016/01/01 16:47:38 0000,2.61,242.5,6.27,8.0,2016-01-01 16:47:38

In [ ]:
#Node 1 Data
wq_data_node1["Hour"] = wq_data_node1["Time"].dt.hour
wq_data_node1["DOW"] = wq_data_node1["Time"].dt.dayofweek
wq_data_node1["Mon"] = wq_data_node1["Time"].dt.month

In [ ]:
wq_data_node2["Hour"] = wq_data_node2["Time"].dt.hour
wq_data_node2["DOW"] = wq_data_node2["Time"].dt.dayofweek
wq_data_node2["Mon"] = wq_data_node2["Time"].dt.month

In [ ]:
wq_data_node1.describe()

,Id,Node Id,Temperature,Conductivity,pH,DissolvedOxygen,Time,Hour,DOW,Mon
count,18378.000000,18378.0,18378.000000,18378.000000,18378.000000,18378.000000,18378,18378.000000,18378.000000,18378.000000
mean,9247.877734,1.0,14.792662,337.740200,5.945226,39.614958,2015-09-07 18:39:15.448253440,11.793394,3.043639,8.720807
min,2.000000,1.0,2.380000,22.800000,0.020000,3.700000,2015-05-01 17:20:48,0.000000,0.000000,1.000000
25%,4620.250000,1.0,10.190000,274.900000,4.810000,11.400000,2015-07-20 10:46:10.500000,6.000000,1.000000,7.000000
50%,9237.500000,1.0,15.590000,317.100000,6.240000,21.300000,2015-09-09 19:30:26.500000,12.000000,3.000000,9.000000
75%,13842.750000,1.0,18.390000,363.675000,7.400000,61.400000,2015-10-28 18:43:51.249999872,18.000000,5.000000,10.000000
max,22033.000000,1.0,28.170000,690.800000,11.500000,149.200000,2016-01-01 16:47:38,23.000000,6.000000,12.000000
std,5359.548117,0.0,5.286647,90.533571,1.864752,35.799224,NaN,6.908384,1.987513,1.925483

In [ ]:
wq_data_node2.describe()

,Id,Node Id,Temperature,Conductivity,pH,DissolvedOxygen,Time,Hour,DOW,Mon
count,5251.000000,5251.0,5251.000000,5251.000000,5251.000000,5251.000000,5251,5251.000000,5251.000000,5251.000000
mean,25862.564464,2.0,16.746163,847.682480,16.026454,25.920777,2015-06-20 07:40:33.181108480,11.988193,3.131784,6.236336
min,23074.000000,2.0,0.020000,0.100000,0.190000,0.000000,2015-05-01 17:17:54,0.000000,0.000000,5.000000
25%,24388.500000,2.0,15.170000,330.800000,6.305000,7.800000,2015-06-07 01:47:51.500000,6.000000,1.000000,6.000000
50%,25701.000000,2.0,17.870000,383.600000,6.820000,19.300000,2015-06-16 08:55:18,12.000000,3.000000,6.000000
75%,27429.500000,2.0,19.580000,450.900000,7.760000,35.600000,2015-07-03 11:39:02,18.000000,5.000000,7.000000
max,29840.000000,2.0,112.620000,26378.700000,94.560000,153.400000,2015-08-31 11:06:03,23.000000,6.000000,8.000000
std,1724.795031,0.0,6.637110,1617.933113,24.862184,28.302458,NaN,6.786756,1.975893,0.686705

In [ ]:
wq_data_node1["hour_sin"] =  np.sin(2 * np.pi * wq_data_node1['Hour'] / 24)
wq_data_node1["hour_cos"] =  np.cos(2 * np.pi * wq_data_node1['Hour'] / 24)

wq_data_node1["DOW_sin"] =  np.sin(2 * np.pi * wq_data_node1['DOW'] / 7)
wq_data_node1["DOW_cos"] =  np.cos(2 * np.pi * wq_data_node1['DOW'] / 7)

wq_data_node1["Mon_sin"] =  np.sin(2 * np.pi * wq_data_node1['Mon'] / 12)
wq_data_node1["Mon_cos"] =  np.cos(2 * np.pi * wq_data_node1['Mon'] / 12)

In [ ]:
wq_data_node2["hour_sin"] =  np.sin(2 * np.pi * wq_data_node2['Hour'] / 24)
wq_data_node2["hour_cos"] =  np.cos(2 * np.pi * wq_data_node2['Hour'] / 24)

wq_data_node2["DOW_sin"] =  np.sin(2 * np.pi * wq_data_node2['DOW'] / 7)
wq_data_node2["DOW_cos"] =  np.cos(2 * np.pi * wq_data_node2['DOW'] / 7)

wq_data_node2["Mon_sin"] =  np.sin(2 * np.pi * wq_data_node2['Mon'] / 12)
wq_data_node2["Mon_cos"] =  np.cos(2 * np.pi * wq_data_node2['Mon'] / 12)

In [ ]:
wq_data_node1.head(5)

,Id,Node Id,Timestamp as DateTime,Temperature,Conductivity,pH,DissolvedOxygen,Time,Hour,DOW,Mon,hour_sin,hour_cos,DOW_sin,DOW_cos,Mon_sin,Mon_cos
1,2,1,2015/05/01 17:20:48 0000,15.22,345.7,7.36,114.7,2015-05-01 17:20:48,17,4,5,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
2,3,1,2015/05/01 17:30:59 0000,15.80,343.9,7.56,114.3,2015-05-01 17:30:59,17,4,5,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
3,4,1,2015/05/01 17:41:10 0000,16.25,339.7,7.00,118.5,2015-05-01 17:41:10,17,4,5,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
5,6,1,2015/05/02 14:36:17 0000,12.67,328.4,6.10,82.2,2015-05-02 14:36:17,14,5,5,-0.500000,-0.866025,-0.974928,-0.222521,0.5,-0.866025
6,7,1,2015/05/02 14:46:28 0000,12.61,329.4,6.36,80.8,2015-05-02 14:46:28,14,5,5,-0.500000,-0.866025,-0.974928,-0.222521,0.5,-0.866025

In [ ]:
wq_data_node2.head(5)

,Id,Node Id,Timestamp as DateTime,Temperature,Conductivity,pH,DissolvedOxygen,Time,Hour,DOW,Mon,hour_sin,hour_cos,DOW_sin,DOW_cos,Mon_sin,Mon_cos
23073,23074,2,2015/05/01 17:17:54 0000,14.96,337.4,6.35,87.1,2015-05-01 17:17:54,17,4,5,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
23074,23075,2,2015/05/01 17:28:05 0000,14.98,337.9,6.77,85.4,2015-05-01 17:28:05,17,4,5,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
23075,23076,2,2015/05/01 17:38:16 0000,15.04,340.3,6.57,84.6,2015-05-01 17:38:16,17,4,5,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
23076,23077,2,2015/05/01 17:48:26 0000,15.10,341.4,6.46,86.7,2015-05-01 17:48:26,17,4,5,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
23077,23078,2,2015/05/02 14:36:34 0000,12.46,297.1,6.30,61.2,2015-05-02 14:36:34,14,5,5,-0.500000,-0.866025,-0.974928,-0.222521,0.5,-0.866025

In [ ]:
#wq_data_node1.drop(columns=["Id", "Node Id", "Timestamp as DateTime", "Hour", "DOW", "Mon"], inplace=True)
wq_data_node1.drop(columns=["Id", "Node Id", "Timestamp as DateTime", "Hour", "DOW", "Mon"], inplace=True)

In [ ]:
wq_data_node2.drop(columns=["Id", "Node Id", "Timestamp as DateTime", "Hour", "DOW", "Mon"], inplace=True)

In [ ]:
wq_data_node1.head()

,Temperature,Conductivity,pH,DissolvedOxygen,Time,hour_sin,hour_cos,DOW_sin,DOW_cos,Mon_sin,Mon_cos
1,15.22,345.7,7.36,114.7,2015-05-01 17:20:48,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
2,15.80,343.9,7.56,114.3,2015-05-01 17:30:59,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
3,16.25,339.7,7.00,118.5,2015-05-01 17:41:10,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
5,12.67,328.4,6.10,82.2,2015-05-02 14:36:17,-0.500000,-0.866025,-0.974928,-0.222521,0.5,-0.866025
6,12.61,329.4,6.36,80.8,2015-05-02 14:46:28,-0.500000,-0.866025,-0.974928,-0.222521,0.5,-0.866025

In [ ]:
wq_data_node2.head()

,Temperature,Conductivity,pH,DissolvedOxygen,Time,hour_sin,hour_cos,DOW_sin,DOW_cos,Mon_sin,Mon_cos
23073,14.96,337.4,6.35,87.1,2015-05-01 17:17:54,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
23074,14.98,337.9,6.77,85.4,2015-05-01 17:28:05,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
23075,15.04,340.3,6.57,84.6,2015-05-01 17:38:16,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
23076,15.10,341.4,6.46,86.7,2015-05-01 17:48:26,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
23077,12.46,297.1,6.30,61.2,2015-05-02 14:36:34,-0.500000,-0.866025,-0.974928,-0.222521,0.5,-0.866025

# Save files with DateTime and Cycles to PINN_WQS_dataset directory

In [ ]:
wq_data_node1.to_csv('/content/drive/My Drive/PINN_WQS_dataset/wq_dataset_node_datetime_1.csv', index=False)

In [ ]:
wq_data_node2.to_csv('/content/drive/My Drive/PINN_WQS_dataset/wq_dataset_node_datetime2.csv', index=False)

# Save files with DateTime and Cycles to PINN_WQS_dataset directory

In [ ]:
wq_data_node1.drop(columns=["Time"], inplace=True)

In [ ]:
wq_data_node2.drop(columns=["Time"], inplace=True)

In [ ]:
wq_data_node1.head()
wq_data_node2.head()

,Temperature,Conductivity,pH,DissolvedOxygen,hour_sin,hour_cos,DOW_sin,DOW_cos,Mon_sin,Mon_cos
23073,14.96,337.4,6.35,87.1,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
23074,14.98,337.9,6.77,85.4,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
23075,15.04,340.3,6.57,84.6,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
23076,15.10,341.4,6.46,86.7,-0.965926,-0.258819,-0.433884,-0.900969,0.5,-0.866025
23077,12.46,297.1,6.30,61.2,-0.500000,-0.866025,-0.974928,-0.222521,0.5,-0.866025

In [ ]:
#wq_data_node1.to_csv('/content/drive/My Drive/PINN_WQS_dataset/wq_dataset_node_cycles_1.csv', index=False)

In [ ]:
#wq_data_node2.to_csv('/content/drive/My Drive/PINN_WQS_dataset/wq_dataset_node_cycles_2.csv', index=False)

In [ ]:
wq_data_node1.to_csv('/content/drive/My Drive/PINN_WQS_dataset/wq_dataset_node_cycles_1_1DO.csv', index=False)

In [ ]:
wq_data_node2.to_csv('/content/drive/My Drive/PINN_WQS_dataset/wq_dataset_node_cycles_2_2DO.csv', index=False)